[program:cdp-logger]
priority=30
command=python3 -u /opt/bin/cdp-logger.py
autostart=false
autorestart=true
startsecs=3
redirect_stderr=true
stdout_logfile=/tmp/cdp-logger-supervisor.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=0
